# Use docker-compose quando sua aplicação tem mais de um serviço.

# Sua API Flask precisa de um banco de dados externo (PostgreSQL, MySQL, Redis, etc.).
# Você quer rodar sua aplicação localmente com um comando simples (docker-compose up).
# Você tem múltiplos containers que precisam se comunicar.

# Se sua aplicação Flask usa apenas SQLite, o docker-compose não é essencial, porque o SQLite é só um arquivo .db.
